/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'TestMsg'
 * message type.
 */

public class TestMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 39;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 23;

    /** Create a new TestMsg of size 39. */
    public TestMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new TestMsg of the given data_length. */
    public TestMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestMsg with the given data_length
     * and base offset.
     */
    public TestMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestMsg using the given byte array
     * as backing store.
     */
    public TestMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public TestMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public TestMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestMsg embedded in the given message
     * at the given base offset.
     */
    public TestMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestMsg embedded in the given message
     * at the given base offset and length.
     */
    public TestMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <TestMsg> \n";
      try {
        s += "  [history.seqno=";
        for (int i = 0; i < 3; i++) {
          s += "0x"+Long.toHexString(getElement_history_seqno(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: history.seqno
    //   Field type: short[]
    //   Offset (bits): 0
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'history.seqno' is signed (false).
     */
    public static boolean isSigned_history_seqno() {
        return false;
    }

    /**
     * Return whether the field 'history.seqno' is an array (true).
     */
    public static boolean isArray_history_seqno() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'history.seqno'
     */
    public static int offset_history_seqno(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 3) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 104;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'history.seqno'
     */
    public static int offsetBits_history_seqno(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 3) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 104;
        return offset;
    }

    /**
     * Return the entire array 'history.seqno' as a short[]
     */
    public short[] get_history_seqno() {
        short[] tmp = new short[3];
        for (int index0 = 0; index0 < numElements_history_seqno(0); index0++) {
            tmp[index0] = getElement_history_seqno(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'history.seqno' from the given short[]
     */
    public void set_history_seqno(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_history_seqno(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'history.seqno'
     */
    public short getElement_history_seqno(int index1) {
        return (short)getUIntBEElement(offsetBits_history_seqno(index1), 8);
    }

    /**
     * Set an element of the array 'history.seqno'
     */
    public void setElement_history_seqno(int index1, short value) {
        setUIntBEElement(offsetBits_history_seqno(index1), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'history.seqno'
     */
    public static int totalSize_history_seqno() {
        return (312 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'history.seqno'
     */
    public static int totalSizeBits_history_seqno() {
        return 312;
    }

    /**
     * Return the size, in bytes, of each element of the array 'history.seqno'
     */
    public static int elementSize_history_seqno() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'history.seqno'
     */
    public static int elementSizeBits_history_seqno() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'history.seqno'
     */
    public static int numDimensions_history_seqno() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'history.seqno'
     */
    public static int numElements_history_seqno() {
        return 3;
    }

    /**
     * Return the number of elements in the array 'history.seqno'
     * for the given dimension.
     */
    public static int numElements_history_seqno(int dimension) {
      int array_dims[] = { 3,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'history.seqno' with a String
     */
    public void setString_history_seqno(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_history_seqno(i, (short)s.charAt(i));
         }
         setElement_history_seqno(i, (short)0); //null terminate
    }

    /**
     * Read the array 'history.seqno' as a String
     */
    public String getString_history_seqno() { 
         char carr[] = new char[Math.min(net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH,3)];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_history_seqno(i) == (char)0) break;
             carr[i] = (char)getElement_history_seqno(i);
         }
         return new String(carr,0,i);
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: history.times
    //   Field type: long[][]
    //   Offset (bits): 8
    //   Size of each element (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'history.times' is signed (false).
     */
    public static boolean isSigned_history_times() {
        return false;
    }

    /**
     * Return whether the field 'history.times' is an array (true).
     */
    public static boolean isArray_history_times() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'history.times'
     */
    public static int offset_history_times(int index1, int index2) {
        int offset = 8;
        if (index1 < 0 || index1 >= 3) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 104;
        if (index2 < 0 || index2 >= 3) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index2 * 32;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'history.times'
     */
    public static int offsetBits_history_times(int index1, int index2) {
        int offset = 8;
        if (index1 < 0 || index1 >= 3) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 104;
        if (index2 < 0 || index2 >= 3) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index2 * 32;
        return offset;
    }

    /**
     * Return the entire array 'history.times' as a long[][]
     */
    public long[][] get_history_times() {
        long[][] tmp = new long[3][3];
        for (int index0 = 0; index0 < numElements_history_times(0); index0++) {
          for (int index1 = 0; index1 < numElements_history_times(1); index1++) {
              tmp[index0][index1] = getElement_history_times(index0,index1);
          }
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'history.times' from the given long[][]
     */
    public void set_history_times(long[][] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
          for (int index1 = 0; index1 < value[index0].length; index1++) {
              setElement_history_times(index0,index1, value[index0][index1]);
          }
        }
    }

    /**
     * Return an element (as a long) of the array 'history.times'
     */
    public long getElement_history_times(int index1, int index2) {
        return (long)getUIntBEElement(offsetBits_history_times(index1, index2), 32);
    }

    /**
     * Set an element of the array 'history.times'
     */
    public void setElement_history_times(int index1, int index2, long value) {
        setUIntBEElement(offsetBits_history_times(index1, index2), 32, value);
    }

    /**
     * Return the total size, in bytes, of the array 'history.times'
     */
    public static int totalSize_history_times() {
        return (312 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'history.times'
     */
    public static int totalSizeBits_history_times() {
        return 312;
    }

    /**
     * Return the size, in bytes, of each element of the array 'history.times'
     */
    public static int elementSize_history_times() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'history.times'
     */
    public static int elementSizeBits_history_times() {
        return 32;
    }

    /**
     * Return the number of dimensions in the array 'history.times'
     */
    public static int numDimensions_history_times() {
        return 2;
    }

    /**
     * Return the number of elements in the array 'history.times'
     * for the given dimension.
     */
    public static int numElements_history_times(int dimension) {
      int array_dims[] = { 3, 3,  };
        if (dimension < 0 || dimension >= 2) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

}
