#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'ThroughputMsg'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 28

# The Active Message type associated with this message.
AM_TYPE = 133

class ThroughputMsg(tinyos.message.Message.Message):
    # Create a new ThroughputMsg of size 28.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=28):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <ThroughputMsg> \n"
        try:
            s += "  [packetsPerSecond=0x%x]\n" % (self.get_packetsPerSecond())
        except:
            pass
        try:
            s += "  [fillBytes=";
            for i in range(0, 26):
                s += "0x%x " % (self.getElement_fillBytes(i) & 0xff)
            s += "]\n";
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: packetsPerSecond
    #   Field type: int
    #   Offset (bits): 0
    #   Size (bits): 16
    #

    #
    # Return whether the field 'packetsPerSecond' is signed (False).
    #
    def isSigned_packetsPerSecond(self):
        return False
    
    #
    # Return whether the field 'packetsPerSecond' is an array (False).
    #
    def isArray_packetsPerSecond(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'packetsPerSecond'
    #
    def offset_packetsPerSecond(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'packetsPerSecond'
    #
    def offsetBits_packetsPerSecond(self):
        return 0
    
    #
    # Return the value (as a int) of the field 'packetsPerSecond'
    #
    def get_packetsPerSecond(self):
        return self.getUIntElement(self.offsetBits_packetsPerSecond(), 16, 1)
    
    #
    # Set the value of the field 'packetsPerSecond'
    #
    def set_packetsPerSecond(self, value):
        self.setUIntElement(self.offsetBits_packetsPerSecond(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'packetsPerSecond'
    #
    def size_packetsPerSecond(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'packetsPerSecond'
    #
    def sizeBits_packetsPerSecond(self):
        return 16
    
    #
    # Accessor methods for field: fillBytes
    #   Field type: short[]
    #   Offset (bits): 16
    #   Size of each element (bits): 8
    #

    #
    # Return whether the field 'fillBytes' is signed (False).
    #
    def isSigned_fillBytes(self):
        return False
    
    #
    # Return whether the field 'fillBytes' is an array (True).
    #
    def isArray_fillBytes(self):
        return True
    
    #
    # Return the offset (in bytes) of the field 'fillBytes'
    #
    def offset_fillBytes(self, index1):
        offset = 16
        if index1 < 0 or index1 >= 26:
            raise IndexError
        offset += 0 + index1 * 8
        return (offset / 8)
    
    #
    # Return the offset (in bits) of the field 'fillBytes'
    #
    def offsetBits_fillBytes(self, index1):
        offset = 16
        if index1 < 0 or index1 >= 26:
            raise IndexError
        offset += 0 + index1 * 8
        return offset
    
    #
    # Return the entire array 'fillBytes' as a short[]
    #
    def get_fillBytes(self):
        tmp = [None]*26
        for index0 in range (0, self.numElements_fillBytes(0)):
                tmp[index0] = self.getElement_fillBytes(index0)
        return tmp
    
    #
    # Set the contents of the array 'fillBytes' from the given short[]
    #
    def set_fillBytes(self, value):
        for index0 in range(0, len(value)):
            self.setElement_fillBytes(index0, value[index0])

    #
    # Return an element (as a short) of the array 'fillBytes'
    #
    def getElement_fillBytes(self, index1):
        return self.getUIntElement(self.offsetBits_fillBytes(index1), 8, 1)
    
    #
    # Set an element of the array 'fillBytes'
    #
    def setElement_fillBytes(self, index1, value):
        self.setUIntElement(self.offsetBits_fillBytes(index1), 8, value, 1)
    
    #
    # Return the total size, in bytes, of the array 'fillBytes'
    #
    def totalSize_fillBytes(self):
        return (208 / 8)
    
    #
    # Return the total size, in bits, of the array 'fillBytes'
    #
    def totalSizeBits_fillBytes(self):
        return 208
    
    #
    # Return the size, in bytes, of each element of the array 'fillBytes'
    #
    def elementSize_fillBytes(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of each element of the array 'fillBytes'
    #
    def elementSizeBits_fillBytes(self):
        return 8
    
    #
    # Return the number of dimensions in the array 'fillBytes'
    #
    def numDimensions_fillBytes(self):
        return 1
    
    #
    # Return the number of elements in the array 'fillBytes'
    #
    def numElements_fillBytes():
        return 26
    
    #
    # Return the number of elements in the array 'fillBytes'
    # for the given dimension.
    #
    def numElements_fillBytes(self, dimension):
        array_dims = [ 26,  ]
        if dimension < 0 or dimension >= 1:
            raise IndexException
        if array_dims[dimension] == 0:
            raise IndexError
        return array_dims[dimension]
    
    #
    # Fill in the array 'fillBytes' with a String
    #
    def setString_fillBytes(self, s):
         l = len(s)
         for i in range(0, l):
             self.setElement_fillBytes(i, ord(s[i]));
         self.setElement_fillBytes(l, 0) #null terminate
    
    #
    # Read the array 'fillBytes' as a String
    #
    def getString_fillBytes(self):
        carr = "";
        for i in range(0, 4000):
            if self.getElement_fillBytes(i) == chr(0):
                break
            carr += self.getElement_fillBytes(i)
        return carr
    
