/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'ThroughputMsg'
 * message type.
 */

public class ThroughputMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 28;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 133;

    /** Create a new ThroughputMsg of size 28. */
    public ThroughputMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new ThroughputMsg of the given data_length. */
    public ThroughputMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ThroughputMsg with the given data_length
     * and base offset.
     */
    public ThroughputMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ThroughputMsg using the given byte array
     * as backing store.
     */
    public ThroughputMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ThroughputMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public ThroughputMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ThroughputMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public ThroughputMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ThroughputMsg embedded in the given message
     * at the given base offset.
     */
    public ThroughputMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ThroughputMsg embedded in the given message
     * at the given base offset and length.
     */
    public ThroughputMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <ThroughputMsg> \n";
      try {
        s += "  [packetsPerSecond=0x"+Long.toHexString(get_packetsPerSecond())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [fillBytes=";
        for (int i = 0; i < 26; i++) {
          s += "0x"+Long.toHexString(getElement_fillBytes(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: packetsPerSecond
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'packetsPerSecond' is signed (false).
     */
    public static boolean isSigned_packetsPerSecond() {
        return false;
    }

    /**
     * Return whether the field 'packetsPerSecond' is an array (false).
     */
    public static boolean isArray_packetsPerSecond() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'packetsPerSecond'
     */
    public static int offset_packetsPerSecond() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'packetsPerSecond'
     */
    public static int offsetBits_packetsPerSecond() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'packetsPerSecond'
     */
    public int get_packetsPerSecond() {
        return (int)getUIntBEElement(offsetBits_packetsPerSecond(), 16);
    }

    /**
     * Set the value of the field 'packetsPerSecond'
     */
    public void set_packetsPerSecond(int value) {
        setUIntBEElement(offsetBits_packetsPerSecond(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'packetsPerSecond'
     */
    public static int size_packetsPerSecond() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'packetsPerSecond'
     */
    public static int sizeBits_packetsPerSecond() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: fillBytes
    //   Field type: short[], unsigned
    //   Offset (bits): 16
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'fillBytes' is signed (false).
     */
    public static boolean isSigned_fillBytes() {
        return false;
    }

    /**
     * Return whether the field 'fillBytes' is an array (true).
     */
    public static boolean isArray_fillBytes() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'fillBytes'
     */
    public static int offset_fillBytes(int index1) {
        int offset = 16;
        if (index1 < 0 || index1 >= 26) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'fillBytes'
     */
    public static int offsetBits_fillBytes(int index1) {
        int offset = 16;
        if (index1 < 0 || index1 >= 26) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return offset;
    }

    /**
     * Return the entire array 'fillBytes' as a short[]
     */
    public short[] get_fillBytes() {
        short[] tmp = new short[26];
        for (int index0 = 0; index0 < numElements_fillBytes(0); index0++) {
            tmp[index0] = getElement_fillBytes(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'fillBytes' from the given short[]
     */
    public void set_fillBytes(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_fillBytes(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'fillBytes'
     */
    public short getElement_fillBytes(int index1) {
        return (short)getUIntBEElement(offsetBits_fillBytes(index1), 8);
    }

    /**
     * Set an element of the array 'fillBytes'
     */
    public void setElement_fillBytes(int index1, short value) {
        setUIntBEElement(offsetBits_fillBytes(index1), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'fillBytes'
     */
    public static int totalSize_fillBytes() {
        return (208 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'fillBytes'
     */
    public static int totalSizeBits_fillBytes() {
        return 208;
    }

    /**
     * Return the size, in bytes, of each element of the array 'fillBytes'
     */
    public static int elementSize_fillBytes() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'fillBytes'
     */
    public static int elementSizeBits_fillBytes() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'fillBytes'
     */
    public static int numDimensions_fillBytes() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'fillBytes'
     */
    public static int numElements_fillBytes() {
        return 26;
    }

    /**
     * Return the number of elements in the array 'fillBytes'
     * for the given dimension.
     */
    public static int numElements_fillBytes(int dimension) {
      int array_dims[] = { 26,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'fillBytes' with a String
     */
    public void setString_fillBytes(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_fillBytes(i, (short)s.charAt(i));
         }
         setElement_fillBytes(i, (short)0); //null terminate
    }

    /**
     * Read the array 'fillBytes' as a String
     */
    public String getString_fillBytes() { 
         char carr[] = new char[Math.min(net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH,26)];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_fillBytes(i) == (char)0) break;
             carr[i] = (char)getElement_fillBytes(i);
         }
         return new String(carr,0,i);
    }

}
