#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'TestADE7753Msg'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 42

# The Active Message type associated with this message.
AM_TYPE = 7

class TestADE7753Msg(tinyos.message.Message.Message):
    # Create a new TestADE7753Msg of size 42.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=42):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <TestADE7753Msg> \n"
        try:
            s += "  [counter=0x%x]\n" % (self.get_counter())
        except:
            pass
        try:
            s += "  [energy=";
            for i in range(0, 10):
                s += "0x%x " % (self.getElement_energy(i) & 0xffffffff)
            s += "]\n";
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: counter
    #   Field type: int
    #   Offset (bits): 0
    #   Size (bits): 16
    #

    #
    # Return whether the field 'counter' is signed (False).
    #
    def isSigned_counter(self):
        return False
    
    #
    # Return whether the field 'counter' is an array (False).
    #
    def isArray_counter(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'counter'
    #
    def offset_counter(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'counter'
    #
    def offsetBits_counter(self):
        return 0
    
    #
    # Return the value (as a int) of the field 'counter'
    #
    def get_counter(self):
        return self.getUIntElement(self.offsetBits_counter(), 16, 1)
    
    #
    # Set the value of the field 'counter'
    #
    def set_counter(self, value):
        self.setUIntElement(self.offsetBits_counter(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'counter'
    #
    def size_counter(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'counter'
    #
    def sizeBits_counter(self):
        return 16
    
    #
    # Accessor methods for field: energy
    #   Field type: long[]
    #   Offset (bits): 16
    #   Size of each element (bits): 32
    #

    #
    # Return whether the field 'energy' is signed (False).
    #
    def isSigned_energy(self):
        return False
    
    #
    # Return whether the field 'energy' is an array (True).
    #
    def isArray_energy(self):
        return True
    
    #
    # Return the offset (in bytes) of the field 'energy'
    #
    def offset_energy(self, index1):
        offset = 16
        if index1 < 0 or index1 >= 10:
            raise IndexError
        offset += 0 + index1 * 32
        return (offset / 8)
    
    #
    # Return the offset (in bits) of the field 'energy'
    #
    def offsetBits_energy(self, index1):
        offset = 16
        if index1 < 0 or index1 >= 10:
            raise IndexError
        offset += 0 + index1 * 32
        return offset
    
    #
    # Return the entire array 'energy' as a long[]
    #
    def get_energy(self):
        tmp = [None]*10
        for index0 in range (0, self.numElements_energy(0)):
                tmp[index0] = self.getElement_energy(index0)
        return tmp
    
    #
    # Set the contents of the array 'energy' from the given long[]
    #
    def set_energy(self, value):
        for index0 in range(0, len(value)):
            self.setElement_energy(index0, value[index0])

    #
    # Return an element (as a long) of the array 'energy'
    #
    def getElement_energy(self, index1):
        return self.getUIntElement(self.offsetBits_energy(index1), 32, 1)
    
    #
    # Set an element of the array 'energy'
    #
    def setElement_energy(self, index1, value):
        self.setUIntElement(self.offsetBits_energy(index1), 32, value, 1)
    
    #
    # Return the total size, in bytes, of the array 'energy'
    #
    def totalSize_energy(self):
        return (320 / 8)
    
    #
    # Return the total size, in bits, of the array 'energy'
    #
    def totalSizeBits_energy(self):
        return 320
    
    #
    # Return the size, in bytes, of each element of the array 'energy'
    #
    def elementSize_energy(self):
        return (32 / 8)
    
    #
    # Return the size, in bits, of each element of the array 'energy'
    #
    def elementSizeBits_energy(self):
        return 32
    
    #
    # Return the number of dimensions in the array 'energy'
    #
    def numDimensions_energy(self):
        return 1
    
    #
    # Return the number of elements in the array 'energy'
    #
    def numElements_energy():
        return 10
    
    #
    # Return the number of elements in the array 'energy'
    # for the given dimension.
    #
    def numElements_energy(self, dimension):
        array_dims = [ 10,  ]
        if dimension < 0 or dimension >= 1:
            raise IndexException
        if array_dims[dimension] == 0:
            raise IndexError
        return array_dims[dimension]
    
