/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'DhvTestMsg'
 * message type.
 */

public class DhvTestMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 4;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 171;

    /** Create a new DhvTestMsg of size 4. */
    public DhvTestMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new DhvTestMsg of the given data_length. */
    public DhvTestMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DhvTestMsg with the given data_length
     * and base offset.
     */
    public DhvTestMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DhvTestMsg using the given byte array
     * as backing store.
     */
    public DhvTestMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DhvTestMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public DhvTestMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DhvTestMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public DhvTestMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DhvTestMsg embedded in the given message
     * at the given base offset.
     */
    public DhvTestMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DhvTestMsg embedded in the given message
     * at the given base offset and length.
     */
    public DhvTestMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <DhvTestMsg> \n";
      try {
        s += "  [id=0x"+Long.toHexString(get_id())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [count=0x"+Long.toHexString(get_count())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [isOk=0x"+Long.toHexString(get_isOk())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: id
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'id' is signed (false).
     */
    public static boolean isSigned_id() {
        return false;
    }

    /**
     * Return whether the field 'id' is an array (false).
     */
    public static boolean isArray_id() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'id'
     */
    public static int offset_id() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'id'
     */
    public static int offsetBits_id() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'id'
     */
    public int get_id() {
        return (int)getUIntBEElement(offsetBits_id(), 16);
    }

    /**
     * Set the value of the field 'id'
     */
    public void set_id(int value) {
        setUIntBEElement(offsetBits_id(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'id'
     */
    public static int size_id() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'id'
     */
    public static int sizeBits_id() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: count
    //   Field type: short, unsigned
    //   Offset (bits): 16
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'count' is signed (false).
     */
    public static boolean isSigned_count() {
        return false;
    }

    /**
     * Return whether the field 'count' is an array (false).
     */
    public static boolean isArray_count() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'count'
     */
    public static int offset_count() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'count'
     */
    public static int offsetBits_count() {
        return 16;
    }

    /**
     * Return the value (as a short) of the field 'count'
     */
    public short get_count() {
        return (short)getUIntBEElement(offsetBits_count(), 8);
    }

    /**
     * Set the value of the field 'count'
     */
    public void set_count(short value) {
        setUIntBEElement(offsetBits_count(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'count'
     */
    public static int size_count() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'count'
     */
    public static int sizeBits_count() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: isOk
    //   Field type: short, unsigned
    //   Offset (bits): 24
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'isOk' is signed (false).
     */
    public static boolean isSigned_isOk() {
        return false;
    }

    /**
     * Return whether the field 'isOk' is an array (false).
     */
    public static boolean isArray_isOk() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'isOk'
     */
    public static int offset_isOk() {
        return (24 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'isOk'
     */
    public static int offsetBits_isOk() {
        return 24;
    }

    /**
     * Return the value (as a short) of the field 'isOk'
     */
    public short get_isOk() {
        return (short)getUIntBEElement(offsetBits_isOk(), 8);
    }

    /**
     * Set the value of the field 'isOk'
     */
    public void set_isOk(short value) {
        setUIntBEElement(offsetBits_isOk(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'isOk'
     */
    public static int size_isOk() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'isOk'
     */
    public static int sizeBits_isOk() {
        return 8;
    }

}
