#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'DipDataMsg'
# message type.
#

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 7

# The Active Message type associated with this message.
AM_TYPE = 98

class DipDataMsg(DipMsg):
    # Create a new DipDataMsg of size 7.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=7):
        DipMsg.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <DipDataMsg> \n"
        try:
            s += "  [key=0x%x]\n" % (self.get_key())
        except:
            pass
        try:
            s += "  [version=0x%x]\n" % (self.get_version())
        except:
            pass
        try:
            s += "  [size=0x%x]\n" % (self.get_size())
        except:
            pass
        try:
            pass
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: key
    #   Field type: int
    #   Offset (bits): 0
    #   Size (bits): 16
    #

    #
    # Return whether the field 'key' is signed (False).
    #
    def isSigned_key(self):
        return False
    
    #
    # Return whether the field 'key' is an array (False).
    #
    def isArray_key(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'key'
    #
    def offset_key(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'key'
    #
    def offsetBits_key(self):
        return 0
    
    #
    # Return the value (as a int) of the field 'key'
    #
    def get_key(self):
        return self.getUIntElement(self.offsetBits_key(), 16, 1)
    
    #
    # Set the value of the field 'key'
    #
    def set_key(self, value):
        self.setUIntElement(self.offsetBits_key(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'key'
    #
    def size_key(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'key'
    #
    def sizeBits_key(self):
        return 16
    
    #
    # Accessor methods for field: version
    #   Field type: long
    #   Offset (bits): 16
    #   Size (bits): 32
    #

    #
    # Return whether the field 'version' is signed (False).
    #
    def isSigned_version(self):
        return False
    
    #
    # Return whether the field 'version' is an array (False).
    #
    def isArray_version(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'version'
    #
    def offset_version(self):
        return (16 / 8)
    
    #
    # Return the offset (in bits) of the field 'version'
    #
    def offsetBits_version(self):
        return 16
    
    #
    # Return the value (as a long) of the field 'version'
    #
    def get_version(self):
        return self.getUIntElement(self.offsetBits_version(), 32, 1)
    
    #
    # Set the value of the field 'version'
    #
    def set_version(self, value):
        self.setUIntElement(self.offsetBits_version(), 32, value, 1)
    
    #
    # Return the size, in bytes, of the field 'version'
    #
    def size_version(self):
        return (32 / 8)
    
    #
    # Return the size, in bits, of the field 'version'
    #
    def sizeBits_version(self):
        return 32
    
    #
    # Accessor methods for field: size
    #   Field type: short
    #   Offset (bits): 48
    #   Size (bits): 8
    #

    #
    # Return whether the field 'size' is signed (False).
    #
    def isSigned_size(self):
        return False
    
    #
    # Return whether the field 'size' is an array (False).
    #
    def isArray_size(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'size'
    #
    def offset_size(self):
        return (48 / 8)
    
    #
    # Return the offset (in bits) of the field 'size'
    #
    def offsetBits_size(self):
        return 48
    
    #
    # Return the value (as a short) of the field 'size'
    #
    def get_size(self):
        return self.getUIntElement(self.offsetBits_size(), 8, 1)
    
    #
    # Set the value of the field 'size'
    #
    def set_size(self, value):
        self.setUIntElement(self.offsetBits_size(), 8, value, 1)
    
    #
    # Return the size, in bytes, of the field 'size'
    #
    def size_size(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of the field 'size'
    #
    def sizeBits_size(self):
        return 8
    
    #
    # Accessor methods for field: data
    #   Field type: short[]
    #   Offset (bits): 56
    #   Size of each element (bits): 8
    #

    #
    # Return whether the field 'data' is signed (False).
    #
    def isSigned_data(self):
        return False
    
    #
    # Return whether the field 'data' is an array (True).
    #
    def isArray_data(self):
        return True
    
    #
    # Return the offset (in bytes) of the field 'data'
    #
    def offset_data(self, index1):
        offset = 56
        if index1 < 0:
            raise IndexError
        offset += 0 + index1 * 8
        return (offset / 8)
    
    #
    # Return the offset (in bits) of the field 'data'
    #
    def offsetBits_data(self, index1):
        offset = 56
        if index1 < 0:
            raise IndexError
        offset += 0 + index1 * 8
        return offset
    
    #
    # Return the entire array 'data' as a short[]
    #
    def get_data(self):
        raise IndexError
    
    #
    # Set the contents of the array 'data' from the given short[]
    #
    def set_data(self, value):
        for index0 in range(0, len(value)):
            self.setElement_data(index0, value[index0])

    #
    # Return an element (as a short) of the array 'data'
    #
    def getElement_data(self, index1):
        return self.getUIntElement(self.offsetBits_data(index1), 8, 1)
    
    #
    # Set an element of the array 'data'
    #
    def setElement_data(self, index1, value):
        self.setUIntElement(self.offsetBits_data(index1), 8, value, 1)
    
    #
    # Return the size, in bytes, of each element of the array 'data'
    #
    def elementSize_data(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of each element of the array 'data'
    #
    def elementSizeBits_data(self):
        return 8
    
    #
    # Return the number of dimensions in the array 'data'
    #
    def numDimensions_data(self):
        return 1
    
    #
    # Return the number of elements in the array 'data'
    # for the given dimension.
    #
    def numElements_data(self, dimension):
        array_dims = [ 0,  ]
        if dimension < 0 or dimension >= 1:
            raise IndexException
        if array_dims[dimension] == 0:
            raise IndexError
        return array_dims[dimension]
    
    #
    # Fill in the array 'data' with a String
    #
    def setString_data(self, s):
         l = len(s)
         for i in range(0, l):
             self.setElement_data(i, ord(s[i]));
         self.setElement_data(l, 0) #null terminate
    
    #
    # Read the array 'data' as a String
    #
    def getString_data(self):
        carr = "";
        for i in range(0, 4000):
            if self.getElement_data(i) == chr(0):
                break
            carr += self.getElement_data(i)
        return carr
    
