/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'RssiSerialMsg'
 * message type.
 */

public class RssiSerialMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 5;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 134;

    /** Create a new RssiSerialMsg of size 5. */
    public RssiSerialMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new RssiSerialMsg of the given data_length. */
    public RssiSerialMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RssiSerialMsg with the given data_length
     * and base offset.
     */
    public RssiSerialMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RssiSerialMsg using the given byte array
     * as backing store.
     */
    public RssiSerialMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RssiSerialMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public RssiSerialMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RssiSerialMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public RssiSerialMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RssiSerialMsg embedded in the given message
     * at the given base offset.
     */
    public RssiSerialMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RssiSerialMsg embedded in the given message
     * at the given base offset and length.
     */
    public RssiSerialMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <RssiSerialMsg> \n";
      try {
        s += "  [rssiAvgValue=0x"+Long.toHexString(get_rssiAvgValue())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [rssiLargestValue=0x"+Long.toHexString(get_rssiLargestValue())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [channel=0x"+Long.toHexString(get_channel())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: rssiAvgValue
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'rssiAvgValue' is signed (false).
     */
    public static boolean isSigned_rssiAvgValue() {
        return false;
    }

    /**
     * Return whether the field 'rssiAvgValue' is an array (false).
     */
    public static boolean isArray_rssiAvgValue() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'rssiAvgValue'
     */
    public static int offset_rssiAvgValue() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'rssiAvgValue'
     */
    public static int offsetBits_rssiAvgValue() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'rssiAvgValue'
     */
    public int get_rssiAvgValue() {
        return (int)getUIntBEElement(offsetBits_rssiAvgValue(), 16);
    }

    /**
     * Set the value of the field 'rssiAvgValue'
     */
    public void set_rssiAvgValue(int value) {
        setUIntBEElement(offsetBits_rssiAvgValue(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'rssiAvgValue'
     */
    public static int size_rssiAvgValue() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'rssiAvgValue'
     */
    public static int sizeBits_rssiAvgValue() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: rssiLargestValue
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'rssiLargestValue' is signed (false).
     */
    public static boolean isSigned_rssiLargestValue() {
        return false;
    }

    /**
     * Return whether the field 'rssiLargestValue' is an array (false).
     */
    public static boolean isArray_rssiLargestValue() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'rssiLargestValue'
     */
    public static int offset_rssiLargestValue() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'rssiLargestValue'
     */
    public static int offsetBits_rssiLargestValue() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'rssiLargestValue'
     */
    public int get_rssiLargestValue() {
        return (int)getUIntBEElement(offsetBits_rssiLargestValue(), 16);
    }

    /**
     * Set the value of the field 'rssiLargestValue'
     */
    public void set_rssiLargestValue(int value) {
        setUIntBEElement(offsetBits_rssiLargestValue(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'rssiLargestValue'
     */
    public static int size_rssiLargestValue() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'rssiLargestValue'
     */
    public static int sizeBits_rssiLargestValue() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: channel
    //   Field type: short, unsigned
    //   Offset (bits): 32
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'channel' is signed (false).
     */
    public static boolean isSigned_channel() {
        return false;
    }

    /**
     * Return whether the field 'channel' is an array (false).
     */
    public static boolean isArray_channel() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'channel'
     */
    public static int offset_channel() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'channel'
     */
    public static int offsetBits_channel() {
        return 32;
    }

    /**
     * Return the value (as a short) of the field 'channel'
     */
    public short get_channel() {
        return (short)getUIntBEElement(offsetBits_channel(), 8);
    }

    /**
     * Set the value of the field 'channel'
     */
    public void set_channel(short value) {
        setUIntBEElement(offsetBits_channel(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'channel'
     */
    public static int size_channel() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'channel'
     */
    public static int sizeBits_channel() {
        return 8;
    }

}
