enum {
  SECOND = 1024UL,
  //MINUTE = SECOND * 60U,
  //HOUR = MINUTE * 60U,
  IRREMOTECON_SCHEDULER_TIMER_PERIOD = 30LU, //minute
};

enum {
  /*
  IRREMOTECON_SET_SCHEDULER_TIMER = 101,
  IRREMOTECON_SET_SCHEDULER_ON = 102,
  IRREMOTECON_SET_SCHEDULER_OFF = 103,
  IRREMOTECON_SET_REMOCON_ON = 0x11,
  IRREMOTECON_SET_REMOCON_OFF = 0x12,
  */
  IRREMOTECON_SET_SCHEDULER_ON = 101,
  IRREMOTECON_SET_SCHEDULER_OFF = 102,
  IRREMOTECON_SET_REMOCON_POWER = 103,
  IRREMOTECON_SET_SCHEDULER_TIMER_SET = 104,

  //SENSING_CODE_INIT = 0x01,
  //SENSING_CODE_INFO = 0x02,
  //SENSING_CODE_ON = 0x11,
  //SENSING_CODE_OFF = 0x12,
};
